### ISSUE TITLE
[Feature Request] Replace youtube-dl.exe with the latest yt-dlp version.

### ISSUE THREAD

**Issue by untuned** [Natsumi-sama/VRCX#21]
As the title states, I'd like there to be an additional button to download, and replace, the `youtube-dl.exe` file in the Tools folder, and mark it as read-only. (additionally un-marking it as read-only if we're updating it)

This has helped me fix issues relating to videos not loading, so I think it might be helpful for other users.

**Comment by Natsumi-sama** [comment]
No, because I would need to keep track of the installed version as well as the lastest version and having to create all of the required settings for that really isn't worth the effort and time. It could be a manual button but that will only cause more problems than it will fix in the long run. e.g. user clicks button once and forgets about it being readonly so it breaks in a month. Make a canny asking VRC to update it more. I can make you a powershell script if you really want.
